### PR TITLE
please enable issues for this repo

### PR DESCRIPTION
**Pull request by matkoniecz**
Can you consider enabling issues for this repo? One obvious thing that may be improved and I have no ready PR for it is including usage instructions (including information whatever it is even possible to use this converter at this moment).

### CODE REVIEW

**Comment by matkoniecz** [comment]
Also at this moment after successful installation of libroxml:

```
sudo make install
[ 22%] Built target roxml-dynamic
[ 45%] Built target roxml-static
[ 47%] Built target roxml-tool
[ 70%] Built target roxml_test
[ 72%] Built target roxml.mem
[ 75%] Built target roxml.perf
[ 91%] Built target roxml_test_tiny
[ 95%] Built target roxml.tiny.unitC
[100%] Built target roxml.unitC
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/lib/libroxml.so.2
-- Up-to-date: /usr/local/lib/libroxml.so.2.3.0
-- Up-to-date: /usr/local/lib/libroxml.so
-- Up-to-date: /usr/local/lib/libroxml.a
-- Up-to-date: /usr/local/bin/roxml
-- Up-to-date: /usr/local/include/roxml.h
```

and compilation

```
make
Compiled coordsTransform.cpp successfully!
Compiled main.cpp successfully!
Compiled osm.cpp successfully!
Compiled rules.cpp successfully!
Compiled timer.cpp successfully!
Compiled xmap.cpp successfully!
Compiled xml.cpp successfully!
Linking complete!
```

it is not working:

`./bin/osm2xmap: error while loading shared libraries: libroxml.so.2.3.0: cannot open shared object file: No such file or directory`

**Comment by matkoniecz** [comment]
Apparently libroxml and this program have cooperation problems.

Un Ubuntu 14.10 libroxml install itself in places not detected by this program. Copying compiled libroxml to /usr/lib allowed to pass `cannot open shared object file` error.

**Comment by matkoniecz** [comment]
Now it would be nice to have documented what "symbol set XMAP file" is and how one may get it...

**Comment by sembruk** [comment]
> Now it would be nice to have documented what "symbol set XMAP file" is and how one may get it...

Ok.

**Comment by matkoniecz** [comment]
moved to issues, thanks for enabling them!

**Pull request closed without merging**
